# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.TimeField(verbose_name='Opening time')),
                ('close', models.TimeField(verbose_name='Closing time')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('nr', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Opening hours rules',
                'verbose_name': 'Opening hours rule',
            },
        ),
    ]
